# Copyright 2024 CS Group
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

default_language_version:
    python: python3
default_stages: [pre-commit]
repos:

# Basic verifications
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-toml
    -   id: check-yaml
        exclude: services/frontend/tests/resources/tools/invalid.yml

# Format (black)
-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black

# Format (isort)
-   repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
    -   id: isort
        args: ["--profile", "black"]

# Format (add trailing commas)
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
    -   id: add-trailing-comma

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
    -   id: pyupgrade
        args: [--py312-plus]

-   repo: https://github.com/pycqa/flake8
    rev: 7.1.2
    hooks:
    -   id: flake8
        args: [--max-complexity=10, --max-line-length=127]

-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        require_serial: true
        args: [--max-line-length=127, "--disable=C0114,C0116,E1102"]

# Remarks:
#   - we don't use ruff because it uses pylint that returns an error code for quality issues
#     that prevents you from commiting your code.
